In [1]:
import snapatac2 as snap
import pandas as pd
import scanpy as sc
import numpy as np
import os
import matplotlib.pyplot as plt
import bin.utils as myutils
lustre_path='/lustre/scratch127/cellgen/cellgeni/tickets/' + os.getcwd().split('/')[4]
lustre_path

'/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942'

In [2]:
satac = sc.read_h5ad(lustre_path+"/work/results_snapatac2_call_peaks_with_blacklist/subset_adatas/peak_mat.h5ad")
satac

AnnData object with n_obs × n_vars = 127107 × 48913
    obs: 'sample', 'leiden', 'celltype'

In [3]:
myutils.addGeneToPeaks(satac,gtf = '/software/cellgen/cellgeni/refdata_10x/refdata-gex-GRCh38-2020-A/genes/genes.gtf',
               upstream=250000,
               downstream=250000)
satac.var

/nfs/cellgeni/tickets/tic-3942/actions/ovary/bin/utils.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['gene_ids'] = [list(nodes.id[g2p.neighbors(inx)]) for inx in regions.inx]
/nfs/cellgeni/tickets/tic-3942/actions/ovary/bin/utils.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['gene_names'] = [list(genes.loc[gids,'gene_name']) for gids in regions.gene_ids]

,gene_ids,gene_names
chr1:826584-827085,"ENSG00000187608,ENSG00000229905,ENSG0000027251...","ISG15,AL669831.2,AL645608.7,SAMD11,AL645608.1,..."
chr1:827301-827802,"ENSG00000223764,ENSG00000187642,ENSG0000018763...","LINC02593,PERM1,SAMD11,PLEKHN1,ISG15,FAM41C,AL..."
chr1:869661-870162,"ENSG00000188290,ENSG00000242590,ENSG0000027344...","HES4,AL645608.5,AL645608.8,KLHL17,AL390719.3,L..."
chr1:904510-905011,"ENSG00000230368,ENSG00000272438,ENSG0000028466...","FAM41C,AL645608.6,OR4F16,PERM1,HES4,LINC01342,..."
chr1:905169-905670,"ENSG00000187583,ENSG00000187608,ENSG0000023036...","PLEKHN1,ISG15,FAM41C,KLHL17,RNF223,AL645608.2,..."
...,...,...
chrX:155745727-155746228,"ENSG00000185973,ENSG00000168939,ENSG00000124333","TMLHE,SPRY3,VAMP7"
chrX:155767379-155767880,"ENSG00000185203,ENSG00000185973,ENSG0000012433...","WASIR1,TMLHE,IL9R,SPRY3,VAMP7"
chrX:155767936-155768437,"ENSG00000124333,ENSG00000124334,ENSG0000016893...","VAMP7,IL9R,SPRY3,TMLHE,WASIR1"
chrX:155881015-155881516,"ENSG00000185973,ENSG00000124334,ENSG0000012433...","TMLHE,IL9R,VAMP7,WASIR1,SPRY3"
chrX:155881530-155882031,"ENSG00000124334,ENSG00000185973,ENSG0000018520...","IL9R,TMLHE,WASIR1,VAMP7,SPRY3"

In [9]:
coors = satac.var_names.str.split('[:-]')
satac.var['chr'] = [x[0] for x in coors]
satac.var['start'] = [int(x[1]) for x in coors]
satac.var['end'] = [int(x[2]) for x in coors]
satac.var

,gene_ids,gene_names,chr,start,end
chr1:826584-827085,"ENSG00000187608,ENSG00000229905,ENSG0000027251...","ISG15,AL669831.2,AL645608.7,SAMD11,AL645608.1,...",chr1,826584,827085
chr1:827301-827802,"ENSG00000223764,ENSG00000187642,ENSG0000018763...","LINC02593,PERM1,SAMD11,PLEKHN1,ISG15,FAM41C,AL...",chr1,827301,827802
chr1:869661-870162,"ENSG00000188290,ENSG00000242590,ENSG0000027344...","HES4,AL645608.5,AL645608.8,KLHL17,AL390719.3,L...",chr1,869661,870162
chr1:904510-905011,"ENSG00000230368,ENSG00000272438,ENSG0000028466...","FAM41C,AL645608.6,OR4F16,PERM1,HES4,LINC01342,...",chr1,904510,905011
chr1:905169-905670,"ENSG00000187583,ENSG00000187608,ENSG0000023036...","PLEKHN1,ISG15,FAM41C,KLHL17,RNF223,AL645608.2,...",chr1,905169,905670
...,...,...,...,...,...
chrX:155745727-155746228,"ENSG00000185973,ENSG00000168939,ENSG00000124333","TMLHE,SPRY3,VAMP7",chrX,155745727,155746228
chrX:155767379-155767880,"ENSG00000185203,ENSG00000185973,ENSG0000012433...","WASIR1,TMLHE,IL9R,SPRY3,VAMP7",chrX,155767379,155767880
chrX:155767936-155768437,"ENSG00000124333,ENSG00000124334,ENSG0000016893...","VAMP7,IL9R,SPRY3,TMLHE,WASIR1",chrX,155767936,155768437
chrX:155881015-155881516,"ENSG00000185973,ENSG00000124334,ENSG0000012433...","TMLHE,IL9R,VAMP7,WASIR1,SPRY3",chrX,155881015,155881516
chrX:155881530-155882031,"ENSG00000124334,ENSG00000185973,ENSG0000018520...","IL9R,TMLHE,WASIR1,VAMP7,SPRY3",chrX,155881530,155882031

In [10]:
satac.write_h5ad(lustre_path+"/work/results_snapatac2_call_peaks_with_blacklist/subset_adatas/peak_mat_with_genes.h5ad")

... storing 'chr' as categorical

In [5]:
patac = sc.read_h5ad(lustre_path+'/work/pycistopic/results_pycistopic_call_peaks/combined.h5ad')
del patac.layers['binary']

In [7]:
myutils.addGeneToPeaks(patac,gtf = '/software/cellgen/cellgeni/refdata_10x/refdata-gex-GRCh38-2020-A/genes/genes.gtf',
               upstream=250000,
               downstream=250000)
patac.var

/nfs/cellgeni/tickets/tic-3942/actions/ovary/bin/utils.py:45: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['gene_ids'] = [list(nodes.id[g2p.neighbors(inx)]) for inx in regions.inx]
/nfs/cellgeni/tickets/tic-3942/actions/ovary/bin/utils.py:46: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  regions['gene_names'] = [list(genes.loc[gids,'gene_name']) for gids in regions.gene_ids]

,gene_ids,gene_names
RegionIDs,,
chr1:831862-832362,"ENSG00000187642,ENSG00000284662,ENSG0000018815...","PERM1,OR4F16,AGRN,NOC2L,FAM87B,AL645608.2,AL64..."
chr1:833362-833862,"ENSG00000273443,ENSG00000284662,ENSG0000022376...","AL645608.8,OR4F16,LINC02593,LINC01409,AL669831..."
chr1:834121-834621,"ENSG00000225880,ENSG00000188976,ENSG0000027243...","LINC00115,NOC2L,AL645608.6,AGRN,LINC01409,AL64..."
chr1:874429-874929,"ENSG00000187642,ENSG00000284662,ENSG0000028581...","PERM1,OR4F16,AL390719.3,C1orf159,NOC2L,AL66983..."
chr1:879007-879507,"ENSG00000272438,ENSG00000188157,ENSG0000027251...","AL645608.6,AGRN,AL645608.7,LINC02593,AL645608...."
...,...,...
chrX:40166524-40167024,"ENSG00000183337,ENSG00000223486,ENSG00000236393","BCOR,AC092198.1,AC091806.1"
chrX:154357329-154357829,"ENSG00000280195,ENSG00000269335,ENSG0000010217...","AC245140.2,IKBKG,UBL4A,SLC10A3,AC244090.3,AC24..."
chrX:25007837-25008337,"ENSG00000004848,ENSG00000101868","ARX,POLA1"
chrX:154359981-154360481,"ENSG00000126903,ENSG00000102119,ENSG0000023183...","SLC10A3,EMD,AC245140.1,TAZ,ATP6AP1,TKTL1,UBL4A..."
chrX:154353271-154353771,"ENSG00000013563,ENSG00000102125,ENSG0000019718...","DNASE1L1,TAZ,AC244090.1,CTAG1A,AC245140.3,TKTL..."

In [11]:
coors = patac.var_names.str.split('[:-]')
patac.var['chr'] = [x[0] for x in coors]
patac.var['start'] = [int(x[1]) for x in coors]
patac.var['end'] = [int(x[2]) for x in coors]
patac.var

,gene_ids,gene_names,chr,start,end
RegionIDs,,,,,
chr1:831862-832362,"ENSG00000187642,ENSG00000284662,ENSG0000018815...","PERM1,OR4F16,AGRN,NOC2L,FAM87B,AL645608.2,AL64...",chr1,831862,832362
chr1:833362-833862,"ENSG00000273443,ENSG00000284662,ENSG0000022376...","AL645608.8,OR4F16,LINC02593,LINC01409,AL669831...",chr1,833362,833862
chr1:834121-834621,"ENSG00000225880,ENSG00000188976,ENSG0000027243...","LINC00115,NOC2L,AL645608.6,AGRN,LINC01409,AL64...",chr1,834121,834621
chr1:874429-874929,"ENSG00000187642,ENSG00000284662,ENSG0000028581...","PERM1,OR4F16,AL390719.3,C1orf159,NOC2L,AL66983...",chr1,874429,874929
chr1:879007-879507,"ENSG00000272438,ENSG00000188157,ENSG0000027251...","AL645608.6,AGRN,AL645608.7,LINC02593,AL645608....",chr1,879007,879507
...,...,...,...,...,...
chrX:40166524-40167024,"ENSG00000183337,ENSG00000223486,ENSG00000236393","BCOR,AC092198.1,AC091806.1",chrX,40166524,40167024
chrX:154357329-154357829,"ENSG00000280195,ENSG00000269335,ENSG0000010217...","AC245140.2,IKBKG,UBL4A,SLC10A3,AC244090.3,AC24...",chrX,154357329,154357829
chrX:25007837-25008337,"ENSG00000004848,ENSG00000101868","ARX,POLA1",chrX,25007837,25008337
chrX:154359981-154360481,"ENSG00000126903,ENSG00000102119,ENSG0000023183...","SLC10A3,EMD,AC245140.1,TAZ,ATP6AP1,TKTL1,UBL4A...",chrX,154359981,154360481
chrX:154353271-154353771,"ENSG00000013563,ENSG00000102125,ENSG0000019718...","DNASE1L1,TAZ,AC244090.1,CTAG1A,AC245140.3,TKTL...",chrX,154353271,154353771

In [17]:
# add celltypes and filer to only annotated cells
celltype = pd.read_csv(lustre_path+'/work/scanvi_out/combined_gene_matrix_plus_ref_clean_scanvi_raw_obs.csv')
celltype.index = celltype.sample_id +":"+celltype.barcode
celltype

,sample_id,barcode,celltype
HCA_P_GON_CZI14524754:AAACGAAGTACGCCCA-1,HCA_P_GON_CZI14524754,AAACGAAGTACGCCCA-1,Stroma_InnCor
HCA_P_GON_CZI14524754:AAACGAATCGCTTGAA-1,HCA_P_GON_CZI14524754,AAACGAATCGCTTGAA-1,Stroma_OutCor_Foll
HCA_P_GON_CZI14524754:AAACGAATCTTTGCAT-1,HCA_P_GON_CZI14524754,AAACGAATCTTTGCAT-1,Stroma_Perifoll_InnCor
HCA_P_GON_CZI14524754:AAACTCGCAAATTGAG-1,HCA_P_GON_CZI14524754,AAACTCGCAAATTGAG-1,Theca_1perifollicular
HCA_P_GON_CZI14524754:AAACTCGGTTAGGCTT-1,HCA_P_GON_CZI14524754,AAACTCGGTTAGGCTT-1,Stroma_InnCor
...,...,...,...
HCA_P_GON_CZI14609780:TTTGTGTGTCTGAGCC-1,HCA_P_GON_CZI14609780,TTTGTGTGTCTGAGCC-1,Stroma_OutCor_Foll
HCA_P_GON_CZI14609780:TTTGTGTGTGGTCGAA-1,HCA_P_GON_CZI14609780,TTTGTGTGTGGTCGAA-1,Stroma_OutCor_Foll
HCA_P_GON_CZI14609780:TTTGTGTGTTCAGTTG-1,HCA_P_GON_CZI14609780,TTTGTGTGTTCAGTTG-1,PV_SMC_Arterial
HCA_P_GON_CZI14609780:TTTGTGTGTTTCCTAT-1,HCA_P_GON_CZI14609780,TTTGTGTGTTTCCTAT-1,Stroma_OutCor_Foll
HCA_P_GON_CZI14609780:TTTGTGTTCGGTTCCT-1,HCA_P_GON_CZI14609780,TTTGTGTTCGGTTCCT-1,Stroma_OutCor_Foll

In [18]:
patac.obs_names = patac.obs.sample_id.astype(str) +":"+patac.obs.barcode.astype(str)
cmn = list(set(celltype.index).intersection(set(patac.obs_names)))
celltype = celltype.loc[cmn,:]
patac = patac[cmn,]
patac.obs['celltype'] = celltype.celltype
patac

/tmp/ipykernel_4134484/1809181087.py:5: ImplicitModificationWarning: Trying to modify attribute `.obs` of view, initializing view as actual.
  patac.obs['celltype'] = celltype.celltype

AnnData object with n_obs × n_vars = 125936 × 645326
    obs: 'cisTopic_nr_frag', 'cisTopic_log_nr_frag', 'cisTopic_nr_acc', 'cisTopic_log_nr_acc', 'sample_id', 'barcode_rank', 'total_fragments_count', 'log10_total_fragments_count', 'unique_fragments_count', 'log10_unique_fragments_count', 'total_fragments_in_peaks_count', 'log10_total_fragments_in_peaks_count', 'unique_fragments_in_peaks_count', 'log10_unique_fragments_in_peaks_count', 'fraction_of_fragments_in_peaks', 'duplication_count', 'duplication_ratio', 'nucleosome_signal', 'tss_enrichment', 'pdf_values_for_tss_enrichment', 'pdf_values_for_fraction_of_fragments_in_peaks', 'pdf_values_for_duplication_ratio', 'barcode', 'celltype'
    var: 'gene_ids', 'gene_names', 'chr', 'start', 'end'

In [19]:
patac.write_h5ad(lustre_path+'/work/pycistopic/results_pycistopic_call_peaks/combined_with_genes.h5ad')

... storing 'celltype' as categorical

# check peaks

In [3]:
satac  = sc.read_h5ad(lustre_path+"/work/results_snapatac2_call_peaks_with_blacklist/subset_adatas/peak_mat_with_genes.h5ad")
satac

AnnData object with n_obs × n_vars = 127107 × 48913
    obs: 'sample', 'leiden', 'celltype'
    var: 'gene_ids', 'gene_names'

In [15]:
patac  = sc.read_h5ad(lustre_path+'/work/pycistopic/results_pycistopic_call_peaks/combined_with_genes.h5ad')
patac

AnnData object with n_obs × n_vars = 144106 × 645326
    obs: 'cisTopic_nr_frag', 'cisTopic_log_nr_frag', 'cisTopic_nr_acc', 'cisTopic_log_nr_acc', 'sample_id', 'barcode_rank', 'total_fragments_count', 'log10_total_fragments_count', 'unique_fragments_count', 'log10_unique_fragments_count', 'total_fragments_in_peaks_count', 'log10_total_fragments_in_peaks_count', 'unique_fragments_in_peaks_count', 'log10_unique_fragments_in_peaks_count', 'fraction_of_fragments_in_peaks', 'duplication_count', 'duplication_ratio', 'nucleosome_signal', 'tss_enrichment', 'pdf_values_for_tss_enrichment', 'pdf_values_for_fraction_of_fragments_in_peaks', 'pdf_values_for_duplication_ratio', 'barcode'
    var: 'gene_ids', 'gene_names', 'chr', 'start', 'end'

In [14]:
gtf='/software/cellgen/cellgeni/refdata_10x/refdata-gex-GRCh38-2020-A/genes/genes.gtf'
genes = myutils.loadGeneFromGTF(gtf)

In [11]:
genes.loc[genes.gene_name=='AMH',]

,0,1,2,3,4,5,6,7,8,gene_id,gene_name
2361421,chr19,HAVANA,gene,2249309,2252073,.,+,.,"gene_id ""ENSG00000104899""; gene_version ""8""; g...",ENSG00000104899,AMH

In [20]:
satac.var.loc[(satac.var.chr=='chr19') & (satac.var.start>2220000) & (satac.var.end < 2260000),]

,gene_ids,gene_names,chr,start,end
chr19:2236138-2236639,"ENSG00000267201,ENSG00000267122,ENSG0000013324...","LINC01775,AC004490.1,BTBD2,AP3D1,AC005258.2,AC...",chr19,2236138,2236639

In [22]:
patac.var.loc[(patac.var.chr=='chr19') & (patac.var.start>2240000) & (patac.var.end < 2242000),]

,gene_ids,gene_names,chr,start,end
RegionIDs,,,,,
chr19:2240846-2241346,"ENSG00000267201,ENSG00000188305,ENSG0000010489...","LINC01775,PEAK3,AMH,TIMM13,SPPL2B,MKNK2,MOB3A,...",chr19,2240846,2241346
chr19:2240266-2240766,"ENSG00000104904,ENSG00000288156,ENSG0000010488...","OAZ1,AC104530.1,PLEKHJ1,LINC01775,AP3D1,IZUMO4...",chr19,2240266,2240766
chr19:2241363-2241863,"ENSG00000172081,ENSG00000176619,ENSG0000009984...","MOB3A,LMNB2,IZUMO4,JSRP1,DOT1L,LSM7,OAZ1,TIMM1...",chr19,2241363,2241863

# export coverage

In [3]:
data = snap.read_dataset(lustre_path+'/work/results_snapatac2_call_peaks_with_blacklist/subset_adatas/_dataset.h5ads')
data

AnnDataSet object with n_obs x n_vars = 127107 x 6062095 backed at '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/subset_adatas/_dataset.h5ads'
contains 23 AnnData objects with keys: 'HCA_P_GON_CZI14609779', 'HCA_P_GON_CZI13941754', 'HCA_P_GON_CZI13941755', 'HCA_P_GON_CZI13941756', 'HCA_P_GON_CZI14666896', 'HCA_P_GON_CZI15033385', 'HCA_P_GON_CZI14666897', 'HCA_P_GON_CZI14609778', 'HCA_P_GON_CZI14524753', 'HCA_P_GON_CZI13737937', 'HCA_P_GON_CZI14524754', 'HCA_P_GON_CZI13941758', 'HCA_P_GON_CZI13654496', 'HCA_P_GON_CZI12220528', 'HCA_P_GON_CZI13941757', 'HCA_P_GON_CZI13187906', 'HCA_P_GON_CZI13941759', 'HCA_P_GON_CZI13941761', 'HCA_P_GON_CZI14666898', 'HCA_P_GON_CZI12220527', 'HCA_P_GON_CZI13941760', 'HCA_P_GON_CZI14609780', 'HCA_P_GON_CZI14524755'
    obs: 'sample', 'leiden', 'celltype', 'tsse'
    var: 'count', 'selected'
    uns: 'reference_sequences', 'frac_overlap_TSS', 'library_tsse', 'spectral_eigenvalue', 'macs3', 'AnnDataSet', 'TSS_profile'
    obsm: 'X_spectral_harmony', 'X_spectral_mnn', 'X_spectral', 'X_umap'
    obsp: 'distances'

In [21]:
snap.ex.export_coverage(data, groupby='celltype',out_dir=lustre_path+'/work/results_snapatac2_call_peaks_with_blacklist/coverage')

2025-06-24 19:53:34 - INFO - Exporting fragments...
2025-06-24 21:14:24 - INFO - Computing coverage...

{'PV_Fibroblast': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/PV_Fibroblast.bw',
 'Stroma_OutCor': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_OutCor.bw',
 'Endo_Cap': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Cap.bw',
 'Immune_MAIT': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_MAIT.bw',
 'Stroma_OutCor_Foll': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_OutCor_Foll.bw',
 'Granulosa_AMH_early': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_AMH_early.bw',
 'Neural_Glia_Adult': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Neural_Glia_Adult.bw',
 'Stroma_Perifoll_OutCor': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_Perifoll_OutCor.bw',
 'Granulosa_sq_transitioning': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_sq_transitioning.bw',
 'Endo_Art': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Art.bw',
 'Immune_Tem_Temra_CD8': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Tem_Temra_CD8.bw',
 'Granulosa_sq_atr': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_sq_atr.bw',
 'Theca_1perifollicular': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_1perifollicular.bw',
 'Immune_Mac_resident_SPP1+': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Mac_resident_SPP1+.bw',
 'Endo_Cap_LY6H+_angiogenic': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Cap_LY6H+_angiogenic.bw',
 'PV_SMC_Arterial': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/PV_SMC_Arterial.bw',
 'Granulosa_AMH_atr': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_AMH_atr.bw',
 'Granulosa_sq': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_sq.bw',
 'Granulosa_AMH_antral': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_AMH_antral.bw',
 'Germcell_Oocyte_I': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Germcell_Oocyte_I.bw',
 'Granulosa_AMH_antral_HedgLow': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_AMH_antral_HedgLow.bw',
 'Endo_Art_LY6H+_angiogenic': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Art_LY6H+_angiogenic.bw',
 'Stroma_InnCor': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_InnCor.bw',
 'Theca_2androgenic_pre': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_2androgenic_pre.bw',
 'Immune_Tcm_Naive_CD4': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Tcm_Naive_CD4.bw',
 'Stroma_Medulla': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_Medulla.bw',
 'FibC3': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/FibC3.bw',
 'Immune_cDC2': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_cDC2.bw',
 'Immune_NK_CD16+': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_NK_CD16+.bw',
 'Theca_2androgenic_Atr': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_2androgenic_Atr.bw',
 'Immune_Mac_resident_LYVE1+_C1QC+': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Mac_resident_LYVE1+_C1QC+.bw',
 'Theca_3structural_ZIM2': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_3structural_ZIM2.bw',
 'Theca_3structural': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_3structural.bw',
 'Immune_B_naive': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_B_naive.bw',
 'Theca_3structural_HedgLow': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_3structural_HedgLow.bw',
 'PV_Capillary_Pericytes': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/PV_Capillary_Pericytes.bw',
 'Immune_Monocytes_cls': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Monocytes_cls.bw',
 'Immune_Tem_Trm_CD8': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Immune_Tem_Trm_CD8.bw',
 'Theca_Atr': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Theca_Atr.bw',
 'Granulosa_AMH_ml': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Granulosa_AMH_ml.bw',
 'Stroma_Perifoll_InnCor': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Stroma_Perifoll_InnCor.bw',
 'Endo_Lymph': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Lymph.bw',
 'Endo_Ven': '/lustre/scratch127/cellgen/cellgeni/tickets/tic-3942/work/results_snapatac2_call_peaks_with_blacklist/coverage/Endo_Ven.bw'}